/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompanycol.diseños;

import com.mycompanycol.dto.DtoLogin;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class Login extends javax.swing.JFrame {
  private DtoLogin login;
  private CardLayout card;
  
   private static final String DB_DRIVER = "org.postgresql.Driver";
    private static final String DB_CONNECTION = "jdbc:postgresql://localhost:5432/factura";
    private static final String DB_USER = "postgres";
    private static final String DB_PASSWORD = "shoutmonx8";
     
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
         crearComponentes2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        jPanel1.setLayout(null);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new java.awt.CardLayout());
        jPanel1.add(jPanel2);
        jPanel2.setBounds(150, 60, 500, 480);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/orig_60311.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

//    private void crearComponentes() {
//        this.enviar.addActionListener((ActionEvent e) -> {
//            boolean save = true;
//            login=new DtoLogin();
//             login.usuario= Usuario.getText() ;
//             login.contraseña= Pass.getText() ;
//                    
//            if(login.usuario.isEmpty()){
//            
//                JOptionPane.showMessageDialog(this, "falta el usuario");
//            
//            }
//            else{
//                
//                 if(login.contraseña.isEmpty()){
//            
//                   JOptionPane.showMessageDialog(this, "falta la contraseña");
//            
//                }
//                 else{
//                       String sql="Select * FROM usuarios WHERE userid='"+login.usuario+"' AND password ='"+login.contraseña+"'";
//                        Connection conet = null;
//                        try{
//                         conet= getDBConnection();
//                         Statement st = conet.createStatement();
//                         ResultSet rs = st.executeQuery(sql);
//                         if(rs.next())
//                         {   JOptionPane.showMessageDialog(this, "entraste");
//                             Formulario form = new Formulario(new java.awt.Frame(),true);
//                             form.setVisible(true);
//                             
//                         }
//                         
//                        }catch(SQLException EX){
//                            JOptionPane.showMessageDialog(this, "error de login");
//                        }finally{
//                            
//                           try {
//                               conet.close();
//                           } catch (SQLException ex) {
//                               Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
//                           }
//                        }
//                 }
//            
//            }
//            
//            
//          
//     
//            });
//    }
//    
    
    private void crearComponentes2(){
        
         this.card=(CardLayout)jPanel2.getLayout();
        registrarse res =  new registrarse (this.jPanel2);
        login2 res2 = new login2(this.jPanel2);
        
        
        
        jPanel2.add(res,"registrarse");
        jPanel2.add(res2,"login2");
        
        
        card.show(jPanel2,"login2");
        
    }
    
//     private static Connection getDBConnection() {
//
//        Connection dbConnection = null;
//
//        try {
//
//            Class.forName(DB_DRIVER);
//
//        } catch (ClassNotFoundException e) {
//
//            System.out.println(e.getMessage());
//
//        }
//
//        try {
//
//            dbConnection = DriverManager.getConnection(DB_CONNECTION, DB_USER,
//                    DB_PASSWORD);
//            return dbConnection;
//
//        } catch (SQLException e) {
//
//            System.out.println(e.getMessage());
//
//        }
//
//        return dbConnection;
//
//    }
}
